### ISSUE TITLE
GraphGist generation changes

### ISSUE THREAD

**Issue by jexp** [neoxygen/graphgen#5]
* [x] limit queries and add //graph_result

````
[source,cypher]
----
MATCH (n:`Country`)
RETURN n
LIMIT 20
----

//graph_result
````

* [x] add //table for meta-graph
* [x] add CHANGEME and TODO in several places (headlines, return aliases) to not have people share unchanged and just generated graphgists

**Comment by ikwattro** [comment]
:+1:

**Comment by ikwattro** [comment]
I guess all points have been fixed. I let the issue open for further points or bugs
