### ISSUE TITLE
More than 1000 nodes and relationships

### ISSUE THREAD

**Issue by FelikZ** [neoxygen/graphgen#6]
Is it possible to create a big graph Cypher / GraphJSON script with more than 1000 nodes?
I do not need a visualization.

Looking for a solution to generate 500k nodes and 500k relationships.

**Comment by ikwattro** [comment]
You can by using the Neogen library in version 1.0.8, the master version contains certain breaking changes

**Comment by FelikZ** [comment]
Thanks!

**Comment by ikwattro** [comment]
Don't hesitate to ping me if help needed, I'm aware that the current doc is not so obvious for command line generation.
